version: "3"
containers:
- name: container
  image: ubuntu
  shell: /bin/bash
  memory: 256
  resources:
    memory: 256
virtualmachines:
- name: myvm
  image: ubuntu-os-cloud/ubuntu-2404-noble-amd64-v20241004
  memory: 4096
  cpus: 1
